- name: Install Java 21
  apt:
    name: openjdk-21-jdk
    state: present
    update_cache: yes

- name: Install dependencies
  apt:
    name:
      - wget
      - tar
    state: present

- name: Create Tomcat group
  group:
    name: "{{ tomcat_group }}"
    state: present

- name: Create Tomcat user
  user:
    name: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    home: /opt/tomcat
    shell: /bin/false
    state: present

- name: Download Tomcat
  get_url:
    url: "{{ tomcat_url }}"
    dest: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"

- name: Create Tomcat directory
  file:
    path: /opt/tomcat
    state: directory
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"

- name: Extract Tomcat
  unarchive:
    src: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"
    dest: /opt/tomcat
    remote_src: yes
    extra_opts: [--strip-components=1]
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"

- name: Configure Tomcat users
  template:
    src: tomcat-users.xml.j2
    dest: /opt/tomcat/conf/tomcat-users.xml
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    mode: '0600'

- name: Set permissions on webapps
  file:
    path: /opt/tomcat/webapps
    state: directory
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    mode: '0775'
    recurse: yes

- name: Make scripts executable
  file:
    path: "/opt/tomcat/bin/{{ item }}"
    mode: '0755'
  loop:
    - startup.sh
    - shutdown.sh
    - catalina.sh

- name: Create Tomcat systemd service
  template:
    src: tomcat.service.j2
    dest: /etc/systemd/system/tomcat.service
  notify: restart tomcat

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Start and enable Tomcat
  systemd:
    name: tomcat
    state: started
    enabled: yes
