---
tomcat_user: tomcat
tomcat_group: tomcat
tomcat_version: 10.1.50
tomcat_url: "https://downloads.apache.org/tomcat/tomcat-10/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
tomcat_manager_user: admin
tomcat_manager_password: password123
